version: '3.6'
x-volumes:
  &default-volumes
  - bundle_cache:/bundle

services:
  app:
    image: "paderinandrey/demo_app"
    env_file:
      - .env
    command: /start.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes: *default-volumes

  db:
    image: postgres:11.2
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=demo_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/11.2/data

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  pgdata:
  bundle_cache:
